begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select plan(46);
insert into auth.users(id,email) values
('20000000-0000-0000-0000-000000000001','finance-a@example.test'),
('20000000-0000-0000-0000-000000000002','finance-b@example.test'),
('20000000-0000-0000-0000-000000000003','finance-viewer@example.test'),
('20000000-0000-0000-0000-000000000004','finance-accountant@example.test');
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-0000-0000-000000000001',true);
select set_config('test.a',public.create_company('Finance A','CO','COP','America/Bogota','Comercio','both',true,array['Centro'])::text,true);
select set_config('test.income',public.save_financial(current_setting('test.a')::uuid,'{"kind":"income","date":"2026-10-07","amount":"100.25","paid":"20.10","description":"Venta QA","category":"product"}')::text,true);
select is((select count(*)::int from receivables),1,'income creates one receivable');
select is((select amount-paid from financial_transactions where id=current_setting('test.income')::uuid),80.15::numeric,'partial income balance exact');
select set_config('test.expense',public.save_financial(current_setting('test.a')::uuid,'{"kind":"expense","date":"2026-10-07","amount":"40.15","paid":"0","description":"Gasto QA","category":"direct"}')::text,true);
select is((select count(*)::int from payables),1,'pending expense creates payable');
select lives_ok($$select save_financial(current_setting('test.a')::uuid,'{"kind":"income","date":"2026-10-07","amount":"200.25","paid":"20.10","description":"Venta editada","category":"product"}',current_setting('test.income')::uuid,(select updated_at from financial_transactions where id=current_setting('test.income')::uuid))$$,'edit movement');
select is((select count(*)::int from receivables),1,'editing does not duplicate linked debt');
select is((select amount-paid from financial_transactions where id=current_setting('test.income')::uuid),180.15::numeric,'editing updates canonical balance');
select lives_ok($$select change_financial(current_setting('test.a')::uuid,current_setting('test.income')::uuid,'close',(select updated_at from financial_transactions where id=current_setting('test.income')::uuid))$$,'close account');
select is((select amount-paid from financial_transactions where id=current_setting('test.income')::uuid),0::numeric,'close settles outstanding');
select lives_ok($$select change_financial(current_setting('test.a')::uuid,current_setting('test.income')::uuid,'restore',(select updated_at from financial_transactions where id=current_setting('test.income')::uuid))$$,'restore account');
select is((select amount-paid from financial_transactions where id=current_setting('test.income')::uuid),180.15::numeric,'restore recovers previous partial payment');
select lives_ok($$select save_financial(current_setting('test.a')::uuid,'{"kind":"expense","date":"2026-10-07","amount":"40.15","paid":"40.15","description":"Gasto QA","category":"direct"}',current_setting('test.expense')::uuid,(select updated_at from financial_transactions where id=current_setting('test.expense')::uuid))$$,'paying linked account through edit works');
select ok((select closed_at is not null from financial_transactions where id=current_setting('test.expense')::uuid),'fully paid linked account closes automatically');
select lives_ok($$select change_financial(current_setting('test.a')::uuid,current_setting('test.expense')::uuid,'restore',(select updated_at from financial_transactions where id=current_setting('test.expense')::uuid))$$,'restore automatically closed account');
select is((select amount-paid from financial_transactions where id=current_setting('test.expense')::uuid),40.15::numeric,'automatic close retains previous balance for restoration');
select throws_ok($$select save_financial(current_setting('test.a')::uuid,'{"kind":"expense","date":"2026-10-07","amount":"1.234","paid":"0","description":"Invalid","category":"direct"}')$$,'22023',null,'reject extra decimals');
select throws_ok($$select save_financial(current_setting('test.a')::uuid,'{"kind":"expense","date":"2026-10-07","amount":"20","paid":"30","description":"Invalid","category":"direct"}')$$,'23514',null,'reject overpayment');
select is((select count(*)::int from financial_transactions),2,'failed writes leave no partial records');
select throws_ok($$update financial_transactions set company_id=gen_random_uuid()$$,'42501',null,'direct table mutation denied');
select throws_ok($$select save_financial(current_setting('test.a')::uuid,'{}',current_setting('test.income')::uuid,'2000-01-01')$$,'40001',null,'stale versions rejected');
select ok((select count(*)>=5 from audit_events where entity='financial_transactions'),'financial mutations audited');
select lives_ok($$select save_financial(current_setting('test.a')::uuid,'{"kind":"asset","date":"2026-10-07","amount":"900","paid":"900","description":"Equipo","category":"equipment","details":{"acquisition":"cash"}}')$$,'asset persists');
select lives_ok($$select save_financial(current_setting('test.a')::uuid,'{"kind":"loan","date":"2026-10-07","amount":"1000","paid":"200","description":"Capital","category":"other","counterparty":"Banco"}')$$,'loan persists');
select is((select count(*)::int from assets),1,'asset entity linked');
select is((select count(*)::int from loans),1,'loan entity linked');
select is(jsonb_typeof(list_financial(current_setting('test.a')::uuid)->0->'amount'),'string','decimal transport is exact text');
select throws_ok($$select save_financial(current_setting('test.a')::uuid,'{"currency":"USD"}')$$,'40001',null,'currency changes reject stale forms');
select set_config('request.jwt.claim.sub','20000000-0000-0000-0000-000000000002',true);
select set_config('test.b',public.create_company('Finance B','CO','COP','America/Bogota','Comercio','both',true,array['Sur'])::text,true);
select set_config('test.location_b',(select id::text from locations limit 1),true);
select is((select count(*)::int from financial_transactions),0,'B cannot read A transactions');
select is((select count(*)::int from receivables),0,'B cannot read A receivables');
select is((select count(*)::int from payables),0,'B cannot read A payables');
select is((select count(*)::int from assets),0,'B cannot read A assets');
select is((select count(*)::int from loans),0,'B cannot read A loans');
select is(list_financial(current_setting('test.a')::uuid),'[]'::jsonb,'list RPC respects RLS');
select throws_ok($$select save_financial(current_setting('test.a')::uuid,'{}')$$,'42501',null,'B cannot write A');
select throws_ok($$select change_financial(current_setting('test.a')::uuid,current_setting('test.income')::uuid,'close',now())$$,'42501',null,'B cannot close A');
select set_config('request.jwt.claim.sub','20000000-0000-0000-0000-000000000001',true);
select throws_ok($$select save_financial(current_setting('test.a')::uuid,jsonb_build_object('kind','expense','date','2026-10-07','amount','20','paid','0','description','Cross location','category','direct','location_id',current_setting('test.location_b')))$$,'42501',null,'foreign location denied');
select throws_ok($$select change_financial(current_setting('test.a')::uuid,current_setting('test.income')::uuid,'delete',(select updated_at from financial_transactions where id=current_setting('test.income')::uuid),'ELIMINAR')$$,'22023',null,'cannot delete source movement');
select set_config('test.manual',save_financial(current_setting('test.a')::uuid,'{"kind":"payable","date":"2026-10-07","amount":"40","paid":"40","description":"Manual","category":"other","counterparty":"Proveedor"}')::text,true);
select ok((select closed_at is not null from financial_transactions where id=current_setting('test.manual')::uuid),'fully paid manual account goes to history');
select throws_ok($$select change_financial(current_setting('test.a')::uuid,current_setting('test.manual')::uuid,'delete',(select updated_at from financial_transactions where id=current_setting('test.manual')::uuid))$$,'22023',null,'delete requires explicit confirmation');
select lives_ok($$select change_financial(current_setting('test.a')::uuid,current_setting('test.manual')::uuid,'delete',(select updated_at from financial_transactions where id=current_setting('test.manual')::uuid),'ELIMINAR')$$,'owner can delete closed manual account');
select ok((select exists(select 1 from audit_events where entity_id=current_setting('test.manual')::uuid and action='delete' and previous_values is not null)),'deletion retains audit');
reset role;
insert into company_memberships(company_id,user_id,role) values(current_setting('test.a')::uuid,'20000000-0000-0000-0000-000000000004','accountant');
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-0000-0000-000000000004',true);
select lives_ok($$select save_financial(current_setting('test.a')::uuid,'{"kind":"receivable","date":"2026-10-07","amount":"20","paid":"0","description":"Accountant entry","category":"other","counterparty":"Cliente"}')$$,'accountant may create');
select set_config('test.accountant',(select id::text from financial_transactions where description='Accountant entry'),true);
select lives_ok($$select change_financial(current_setting('test.a')::uuid,current_setting('test.accountant')::uuid,'close',(select updated_at from financial_transactions where id=current_setting('test.accountant')::uuid))$$,'accountant may close');
select throws_ok($$select change_financial(current_setting('test.a')::uuid,current_setting('test.accountant')::uuid,'delete',(select updated_at from financial_transactions where id=current_setting('test.accountant')::uuid),'ELIMINAR')$$,'22023',null,'accountant cannot permanently delete');
reset role;
insert into company_memberships(company_id,user_id,role) values(current_setting('test.a')::uuid,'20000000-0000-0000-0000-000000000003','viewer');
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-0000-0000-000000000003',true);
select is((select count(*)::int from financial_transactions),5,'viewer reads own company');
select throws_ok($$select save_financial(current_setting('test.a')::uuid,'{}')$$,'42501',null,'viewer cannot write');
set local role anon;
select throws_ok($$select * from financial_transactions$$,'42501',null,'anonymous cannot read finance');
select * from finish();rollback;
